spring:
  application:
    name: template-service
  profiles:
    active: dev
  #设置此属性 dubbo的@service 和 spring的 @Transactional即可以共存，可以正常发布服务了
  aop:
    proxy-target-class: false
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
#mybatis
mybatis-plus:
#把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
  mapperLocations: classpath*:/mapper.setting/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  level:
    root: info
    com.fantaike.template: debug

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql #数据库方言
  reasonable: true      #分页合理化
  support-methods-arguments: true #是否支持接口参数来传递分页参数，默认false
  page-size-zero: true #当设置为true的时候，如果pagesize设置为0（或RowBounds的limit=0），就不执行分页，返回全部结果
  params: count=countSql
