spring:
  datasource:
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/template?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    filters: stat,wall,log4j
    maxActive: 100
    initialSize: 20
    maxWait: 60000
    minIdle: 0
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 25200000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    maxPoolPreparedStatementPerConnectionSize: 33
    removeAbandonedTimeout: 1800
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 0
    expireTime: 86400

dubbo:
  application:
    id: template-service
    name: template-service
  protocol:
    port: 20885
  provider:
    timeout: 600000
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    basePackages: com.fantaike.template
