spring:
  application:
    name: template-web
  profiles:
    active: dev
#logging  不同的目录不同的日志输出级别
logging:
  level:
    root: info
    com.fantaike.template: info

token:
  #  token有效时间，单位分钟 24*60=1440
  tokenExpireTime: 1440
  # 更新令牌时间 2*60=120
  refreshCheckTime: 120
  #  token加密密钥
  secretKey: template-token